unit TestObj.SSI.ICryptString;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Obj.SSI.ICryptString;

type
  // Test methods for class ICryptString

  TestICryptString = class(TTestCase)
  strict private
    const
      cText    = 'Hello World';
      cCrypted = 'ZMTn0ozudfXVWO8=';
    var
      FICryptString: ICryptString;
      FIDecryptString: ICryptString;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCrypt;
    procedure TestDecrypt;
  end;

implementation

procedure TestICryptString.SetUp;
begin
     FICryptString   := TCryptString.New(cText);
     FIDecryptString := TCryptString.New(cCrypted);
end;

procedure TestICryptString.TearDown;
begin
     FICryptString   := nil;
     FIDecryptString := nil;
end;

procedure TestICryptString.TestCrypt;
var
   ReturnValue: String;
begin
     ReturnValue := FICryptString.Crypt.ToString;
     CheckEquals(cCrypted, ReturnValue);
end;

procedure TestICryptString.TestDecrypt;
var
   ReturnValue: String;
begin
     ReturnValue := FIDecryptString.Decrypt.ToString;
     CheckEquals(cText, ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestICryptString.Suite);
end.

