unit TestObj.SSI.IBase64;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Obj.SSI.IBase64;

type
  // Test methods for class IBase64

  TestIBase64 = class(TTestCase)
  strict private
    const
      cText   = 'Hello World';
      cBase64 = 'SGVsbG8gV29ybGQ=';
    var
       FIBase64: IBase64;
       FIText  : IBase64;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestEncode;
    procedure TestDecode;
  end;

implementation

procedure TestIBase64.SetUp;
begin
     FIBase64 := TBase64.New(cText);
     FIText   := TBase64.New(cBase64);
end;

procedure TestIBase64.TearDown;
begin
     FIBase64 := nil;
     FIText   := nil;
end;

procedure TestIBase64.TestEncode;
var
   ReturnValue: String;
begin
     ReturnValue := FIBase64.Encode.ToString;
     CheckEquals(cBase64, ReturnValue);
end;

procedure TestIBase64.TestDecode;
var
   ReturnValue: String;
begin
     ReturnValue := FIText.Decode.ToString;
     CheckEquals(cText, ReturnValue);
end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TestIBase64.Suite);
end.

