unit TestObj.SSI.IDataStream;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, Obj.SSI.IDataStream;

type
  // Test methods for class TDataStream

  TestTDataStream = class(TTestCase)
  strict private
    FDataStreamString: IDataStream;
  private

  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSaveStream;
    procedure TestSaveTStrings;
    procedure TestAsString;
    procedure TestSize;
  end;

implementation

uses
    SysUtils
  ;

procedure TestTDataStream.SetUp;
var
   s: String;
begin
     s := 'xpto';
     FDataStreamString := TDataStream.New(s);
end;

procedure TestTDataStream.TearDown;
begin
     FDataStreamString := nil;
end;

procedure TestTDataStream.TestSaveStream;
var
  ReturnValue: IDataStream;
  SS: TStringStream;
begin
     SS := TStringStream.Create;
     try
        ReturnValue := FDataStreamString.Save(SS);
        CheckEquals('xpto', SS.DataString);
     finally
        SS.Free;
     end;
end;

procedure TestTDataStream.TestSaveTStrings;
var
  ReturnValue: IDataStream;
  Strings: TStringList;
begin
     Strings := TStringList.Create;
     try
        ReturnValue := FDataStreamString.Save(Strings);
        CheckEquals('xpto', Strings[0]);
     finally
        Strings.Free;
     end;
end;

procedure TestTDataStream.TestAsString;
var
  ReturnValue: string;
begin
  ReturnValue := FDataStreamString.AsString;
  CheckEquals('xpto', ReturnValue);
end;

procedure TestTDataStream.TestSize;
var
  ReturnValue: Int64;
begin
  ReturnValue := FDataStreamString.Size;
  CheckEquals(4, ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDataStream.Suite);
end.

